### ISSUE TITLE
usePersistedState — Should first useEffect have dependencies?

### ISSUE THREAD

**Issue by kkirsche** [30-seconds/30-seconds-of-react#117]
In [`usePersistedState.md`](https://github.com/30-seconds/30-seconds-of-react/blob/master/snippets/usePersistedState.md), the following function is shown:

```javascript
  React.useEffect(() => {
    try {
      const storedValue = localStorage.getItem(name);
      if (storedValue !== null) setValue(storedValue);
      else localStorage.setItem(name, defaultValue);
    } catch {
      setValue(defaultValue);
    }
  }, []);
```

I was wondering if it should have the `defaultValue` and `name` as dependencies to allow the hook to be re-initialized even if it was already mounted?

```javascript
  React.useEffect(() => {
    try {
      const storedValue = localStorage.getItem(name);
      if (storedValue !== null) setValue(storedValue);
      else localStorage.setItem(name, defaultValue);
    } catch {
      setValue(defaultValue);
    }
  }, [defaultValue, name]);
```

If not, would it make sense to expand the example/documentation to include a note about eslint react-hook dependency warnings that may trigger, to avoid confusion about whether there is a bug in the implementation or if eslint is unaware of the context as to why the choice was made.

Thanks for your time and consideration.

**Comment by Chalarangelo** [comment]
That's a pretty good observation. We'll take a look and see if we should include dependencies or not, as the ESLint rule can be a bit of a hassle to deal with indeed.

**Comment by Chalarangelo** [comment]
This is safe to use as-is. If ESLint is bothering you, you can either add the dependencies yourself in your code (iff you are certain they will not change after the first render) or have ESLint ignore this line.
