### ISSUE TITLE
[CHORE] Linter

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-react#25]
We definitely need a linter/formatter for snippets, like `eslint` + `prettier` only that it has to work with JSX, too. Can someone please suggest some options and/or help implement them?

**Comment by skatcat31** [comment]
`eslint` has a `JSX` plugin as https://www.npmjs.com/package/eslint-plugin-react that could probably help 😉

**Comment by fejes713** [comment]
@meetzaveri good point, but the only problem with this is that our snippet's are stored in `.md` files, so we need a way to prettier only the parts inside backticks (```jsx);

**Comment by meetzaveri** [comment]
Oh @fejes713 ! Got the point.
