### ISSUE TITLE
Convert all snippets to use hooks

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-react#36]
[Hooks](https://reactjs.org/docs/hooks-intro.html) have been officially merged and will be released soon, they're the recommended way to create components moving forward.

> When you’re ready, we’d encourage you to start trying Hooks in new components you write. 

I think we should discourage using classes and use function components + hooks for everything. This also negates the "public class fields" debate that was happening here last year lol.

**Comment by Chalarangelo** [comment]
Yep, I agree with this 100%. Fewer patterns to learn, more consistent, more in line with our other projects and generally less complicated. Let's start transforming existing snippets and updating PRs before merging, then!
