### ISSUE TITLE
[CHORE] Continuous Integration

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-react#5]
As usual, we have to set up Travis CI, let the bot do its thing and make daily builds and on-demand builds. of the repo.

**Comment by nikolalsvk** [comment]
I'm interested in doing this :)

**Comment by mwaz** [comment]
Is this still up or I could take it up @nikolalsvk ?

**Comment by Chalarangelo** [comment]
Resolved a couple of weeks back, closing...
