### ISSUE TITLE
LimitedTextarea: A little additional detail on useEffect

### ISSUE THREAD

**Issue by Jeddf** [30-seconds/30-seconds-of-react#50]
Thanks for these snippets! 🎉

The LimitedTextarea snippet sent me on a good learning journey about useEffect, these tweaks would have got me there a little faster I think:

- A few more words about the result of the useEffect dependency array.
- Add limit to the useEffect dependencies.
- Value -> initialValue to express the behaviour a bit more specifically.

Got a [commit here](https://github.com/jeddf/30-seconds-of-react/commit/e5995c38488e32ea1f0524d39afc51bde2fc6681) with proposed changes.

I'll turn it into a PR if there's positive feedback.

Hoping to make some more substantial contributions soon!

P.S here's a sandbox I setup to test out the changes: https://codesandbox.io/s/yq177rjz9x

**Comment by louisjordan** [comment]
Hey bug, just noticed a [small issue with your proposed changes](https://github.com/jeddf/30-seconds-of-react/commit/e5995c38488e32ea1f0524d39afc51bde2fc6681#r32577899)
