### ISSUE TITLE
[CountDown]something wrong with this component

### ISSUE THREAD

**Issue by Paleless** [30-seconds/30-seconds-of-react#58]
hi, l think some code in CountDown component may be not right,
![image](https://user-images.githubusercontent.com/36239113/56810492-05d1c880-6869-11e9-97fd-cb9b3960bb9c.png)

l think this is not the rihgt way in using hooks, it will always clearinterval after every render, just like this
![image](https://user-images.githubusercontent.com/36239113/56810638-5cd79d80-6869-11e9-830a-821a4173c60a.png)
l think this need to be fixed, l can do it if you need :)

**Comment by skatcat31** [comment]
it SHOULD clear the interval every render because it is setting one every render. Otherwise you get a memory leak.

It can however be cleaned up:

```js
React.useEffect(() => {
  const timerID =setInterval(tick, 1000);
  return () => clearInterval(timerID)
});
```
