### ISSUE TITLE
Wrong link to Input example in the table of content

### ISSUE THREAD

**Issue by RinatValiullov** [30-seconds/30-seconds-of-react#62]
I noticed that there's wrong link to _Input_ example in the table of content. It doesn't match:

`https://github.com/30-seconds/30-seconds-of-react#input` - actual(wrong)
`https://github.com/30-seconds/30-seconds-of-react#input-2` - in the content

**Comment by Chalarangelo** [comment]
Correct. The names of the snippet and the category clash with each other. I'll see what I can do.
