### ISSUE TITLE
MailTo Encoding

### ISSUE THREAD

**Issue by samuelcolburn** [30-seconds/30-seconds-of-react#66]
1. Using special characters in `mailto:` strings causes Outlook (and possibly other email clients) to stop parsing the string.

Example:

```jsx
ReactDOM.render(
  <Mailto email="foo@bar.baz" subject="Hello & Welcome" body="Hello & Welcome world!">
    Mail me!
  </Mailto>,
  document.getElementById('root')
);

// result: mailto will stop being parsed at the first ampersand, ignoring the body
```

Suggestion: Encode `subject` and `body` strings:

```jsx
function Mailto({ email, subject, body, ...props }) {
  return (
    <a href={`mailto:${email}?subject=${encodeURIComponent(subject) || ''}&body=${encodeURIComponent(body) || ''}`}>{props.children}</a>
  );
}
```

**Comment by Dusch4593** [comment]
I tested this on Codepen and this seems to do the trick!

**Comment by Chalarangelo** [comment]
I would gladly merge a PR for this, if any of you can make the necessary changes.

**Comment by Dusch4593** [comment]
I forked a copy of the repo to my local and made changes to the specific snippet file (Mailto.md). This was my **very**first pull request on GitHub like ever so hopefully I did it right and respected the terms of the CONTRIBUTING.md file. Please let me know if it worked fine and what I should do going forward regarding PRs.

**Comment by Chalarangelo** [comment]
@Dusch4593 I don't see the PR...

**Comment by Dusch4593** [comment]
I think I got it. Check to see if it's there now.
