### ISSUE TITLE
adding test suite for components and hooks

### ISSUE THREAD

**Issue by sagar-gavhane** [30-seconds/30-seconds-of-react#91]
## Description
Hi,

This is one of the extremely helpful projects I've ever seen. In this issue, I want to discuss "**Do you've any plan to add test suite?**". Sometimes I feel like we're using snippets on production so we need to have a test suite which will give us solid confidence.

Anyway, Thanks for maintaining this project.

**Comment by Chalarangelo** [comment]
Thanks for the feedback. We are not currently planning to add a test suite as we do not have the resources to maintain it, but it might be something we look into the future. I am marking as an enhancement and adding it to the workboard.

**Comment by sagar-gavhane** [comment]
Thanks @Chalarangelo for recording feedback.

**Comment by Chalarangelo** [comment]
Due to limited resources and seeing how 30code's test suite has fallen into disuse lately, I will close this as it will be postponed indefinitely and reopen if we find the time to put in the effort to implement this later down the line.
